### ISSUE TITLE
how this works

### ISSUE THREAD

**Issue by gabrieru** [nathan242/php-rtsp-client#1]
hello, im trying to get video streaming from my cameras on this protocol, the php test dont working for me
my params are:
rtsp://my-ip:8854/live0.264?user=myadmin&passwd=mypass
rtsp://my-ip:8854/live2.264?user=myadmin&passwd=mypass
rtsp://my-ip:8854/live4.264?user=myadmin&passwd=mypass
rtsp://my-ip:8854/live6.264?user=myadmin&passwd=mypass
rtsp://my-ip:8854/live8.264?user=myadmin&passwd=mypass

**Comment by nathan242** [comment]
This RTSP class will only handle the RTSP protocol which is used to control streaming from a device. You can use this class to configure and activate a RTP stream to a specific port but you will need an application capable of receiving it. You will also need to get the SDP data from the RTSP SETUP response.

The "rtsp-test.php" file is intended to be a simple usage example for the "rtsp_client" class. You should write your own PHP script using this class to control a device via RTSP and have a separate system for capturing/processing the actual media streams.

I originally created this for another project but it was not used and is only a basic implementation of a RTSP client. You may need to add more code to the class to get it working for certain uses.
