### ISSUE TITLE
Make this into something useful!

### ISSUE THREAD

**Issue by nathan242** [nathan242/php-rtsp-client#2]
Make this into something useful.

It appears that many people have a use for handling RTSP media devices from PHP. I do not have much time to work on completing this. Please feel free to contribute to this to make it into something useful!

**Comment by kmkmahesh** [comment]
Hi Nathan,

i just want to make an php webpage, which can hide the credentials of the device, how to play the live view with this script.

I am just getting the below output at my page if i am using   

`$url = "rtsp://172.17.0.30:554/cam/realmonitor?channel=1&subtype=0";`

Output
`22222`

if 
`$url = "554/cam/realmonitor?channel=1&subtype=0";`

Output
`Array ( [proto] => RTSP/1.0 [code] => 200 [msg] => OK [CSeq] => 1 [Server] => Rtsp Server/3.0 [Public] => OPTIONS, DESCRIBE, ANNOUNCE, SETUP, PLAY, RECORD, PAUSE, TEARDOWN, SET_PARAMETER, GET_PARAMETER [] => ) Array ( [proto] => RTSP/1.0 [code] => 503 [msg] => Service [CSeq] => 2 [] => ) Array ( [proto] => [code] => [msg] => ) Array ( [proto] => [code] => [msg] => ) Array ( [proto] => [code] => [msg] => )`

Working URL in VLC is 
`rtsp://admin:mypassword@CAMS@172.17.0.30:554/cam/realmonitor?channel=1&subtype=0`

**Comment by nathan242** [comment]
This library only handles the RTSP protocol. The actual media will be streamed using another protocol (such as RTP) which is not handled by this library. I have recently updated the code so it is now possible to correctly retrieve the SDP data (which contains information about the format of the media streams) via RTSP.

RTSP is only a control protocol for activating media streams so you will need another application that can pass the actual media to the webpage in a suitable format. I don't currently know of a way to do this.
